Added unit tests, dockerfile, minor code changes.
ophicleide/ophicleide-training pull request #19
Opened 2017-07-10 15:36 UTC by HumairAK

Hello! The following changes are included in this PR:

**Tests**
The testing framework used is pytest. You can find all the dependencies used in the requirements-tests.txt and the tox.ini (under deps). Tests can be ran by simply invoking the `tox` command in the terminal (in the directory in which tox.ini resides) after cloning. After the first tox invocation, any consecutive test runs will run faster. Some resource files for testing purposes are also included. 

**Docker-CI file**
Docker file was submitted by [dsoukhov](https://github.com/dsoukhov) for CI purposes. 

**Changes to code base** 
The following changes were made: 
- Minor code changes to follow pep8 specification. 
- Refactored code in `workloop` method in `worker.py` to make it more testable (simply moved to a new method `update_model`). 
- `options() `global is now defined within a global configs file called `conf.py `and initialized in `app.py.` Initially `options()` was imported in `defaultcontrollers.py` by the calling script via the 'from __main__ import options' command. This setup made it impossible to unit test `defaultcontrollers.py.` 

Please do let me know if there are any issues at your leisure, 
Thanks!

2017-07-10 15:40 UTC, zmhassan commented
I spoke with @elmiko and asked him to review this patch. @HumairAK thanks for your contribution.

2017-07-11 19:58 UTC, elmiko requested changes
this looks really nice @HumairAK, i have a couple questions and one request.

i noticed that building the container image from the Dockerfile-ci looks like it is running the tests during the build phase, is this by design?

i would have expected the Dockerfile-ci to produce an image that runs the tests, is there something i am missing about our CI setup?

would you mind adding text to the README.md file about how to run the tests

2017-07-11 20:00 UTC, elmiko commented on Dockerfile-ci
> + && tox
this is running the test during image creation, is that the expected behavior?

2017-07-11 21:22 UTC, dsoukhov commented
I designed the dockerfile-ci to run the test during image creation. I have a jenkins build set up on et.24 that uses it for automated testing. If a test fails, the build also fails. 

I'll add some info to the readme on how to run the tests.

2017-07-11 21:29 UTC, elmiko commented
excellent, thanks @dsoukhov !

2017-07-12 15:59 UTC, elmiko commented
thanks for the updates @HumairAK and @dsoukhov lgtm!

2017-07-12 16:31 UTC, willb commented
Thanks, guys!

2017-07-12 16:31 UTC, merged